version: "3.8"

services:
  api:
    build: .
    container_name: fastapi_app

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: sqlite+aiosqlite:///./app.db
      SECRET_KEY: change-me

    volumes:
      - .:/app

    restart: always


